# Generated by Django 4.0.6 on 2022-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventType', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop')], max_length=256)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('organizer', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=256)),
                ('picture', models.ImageField(blank=True, default='../media/eventpic/icon-0.jpg', upload_to='eventpic')),
            ],
        ),
    ]
