# Generated by Django 4.0.6 on 2022-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventType', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition')], max_length=256)),
                ('startDateTime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=256)),
                ('picture', models.ImageField(upload_to='eventpic')),
            ],
        ),
    ]
