# Generated by Django 4.0.6 on 2022-11-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='endDate',
            field=models.DateField(default='2018-12-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='startDate',
            field=models.DateField(default='2018-12-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='eventType',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition')], default='Hackathon', max_length=256),
        ),
    ]
