# Generated by Django 4.0.6 on 2022-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='body',
            field=models.TextField(max_length=3840),
        ),
    ]
