# Generated by Django 4.0.6 on 2022-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_alter_eventmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='eventType',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition')], default=('Hackathon', 'Hackathon'), max_length=256),
        ),
    ]
