# Generated by Django 4.0.6 on 2022-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], default='Photo', max_length=256)),
                ('content', models.FileField(default='../media/eventpic/icon-0.jpg', upload_to='gallery')),
            ],
        ),
    ]
