# Generated by Django 4.0.6 on 2022-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='gallery')),
                ('caption', models.CharField(max_length=256)),
            ],
        ),
    ]
