# Generated by Django 4.0.6 on 2022-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='content',
            field=models.FileField(upload_to='gallery'),
        ),
    ]
