# Generated by Django 4.0.6 on 2022-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='caption',
            field=models.CharField(default='Caption', max_length=256),
            preserve_default=False,
        ),
    ]
