# Generated by Django 4.0.6 on 2022-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryitem_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='type',
            field=models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video'), ('YouTube', 'YouTube')], default='Photo', max_length=256),
        ),
    ]
