# Generated by Django 4.0.6 on 2022-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_galleryitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='type',
            field=models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], default='Photo', max_length=256),
        ),
    ]
