# Generated by Django 4.0.6 on 2022-11-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_productimage_alter_galleryitem_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
