# Generated by Django 4.0.6 on 2022-11-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('caption', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('caption', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryYouTubeVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('embedcode', models.TextField()),
                ('caption', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
