# Generated by Django 4.0.6 on 2022-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_galleryphoto_galleryvideo_galleryyoutubevideo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryVideo',
        ),
        migrations.DeleteModel(
            name='GalleryYouTubeVideo',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='file',
            field=models.FileField(default='file.jpg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
