# Generated by Django 4.0.6 on 2022-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_delete_galleryvideo_delete_galleryyoutubevideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='file',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
