# Generated by Django 4.0.6 on 2022-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=356)),
                ('answer', models.CharField(max_length=356)),
            ],
        ),
    ]
