# Generated by Django 4.0.6 on 2022-12-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='../media/profile/img6Q.png', upload_to='profile')),
            ],
        ),
    ]
