# Generated by Django 4.0.6 on 2022-12-04 10:13

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='../static/assets/img6Q.png', upload_to='profile'),
        ),
    ]
